name: Lets Start AyraRobot
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "and user not in [777000, 1087968824]"
          replace: "and user not in [777000, 1087968824, 1356469075]"
      - name: Pull All Updates
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'AyraRobot'
          commit_options: '--no-verify'
          repository: .
          commit_user_name: BANNA-XD143
          commit_user_email: 102808014+BANNA-XD143@users.noreply.github.com
          commit_author: BANNA-XD143 <102808014+BANNA-XD143@users.noreply.github.com>
